# Generated by Django 2.2.4 on 2019-08-21 09:25

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190821_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='content_stream',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True))])), ('full_richText', streams.blocks.RichTextBlock()), ('simple_richText', streams.blocks.SimpleRichTextBlock()), ('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Title of your card', max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Description of your card', max_length=200, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='if the button page above is selected, that will be used first', required=False))])))]))], blank=True, null=True),
        ),
    ]
