# Generated by Django 2.2.4 on 2019-08-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogdetailpage_blog_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='blog_image',
            new_name='banner_image',
        ),
    ]
