# Generated by Django 2.2.4 on 2019-08-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_articleblogpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleblogpage',
            old_name='intro_mage',
            new_name='intro_image',
        ),
    ]
