# Generated by Django 2.2.4 on 2019-08-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190825_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
