# Generated by Django 2.2.4 on 2019-08-21 10:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190820_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_stream',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Add your text', required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(help_text='Add your page/post url', required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='Add your Button Url', required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Read more', help_text='Add your button text', max_length=40, required=False))]))], blank=True, null=True),
        ),
    ]
