# Generated by Django 2.2.4 on 2019-08-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Your email', max_length=100)),
                ('full_name', models.CharField(help_text='Full name', max_length=100)),
            ],
        ),
    ]
