# Generated by Django 2.2.4 on 2019-08-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20190822_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subcriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
