# Generated by Django 2.2.4 on 2019-08-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_auto_20190822_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.CharField(help_text='Email address', max_length=255),
        ),
    ]
